### ISSUE TITLE
Firfox extension has been removed

### ISSUE THREAD

**Issue by chefBrian** [philiannuzzo/fanlights#3]
Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

**Comment by philiannuzzo** [comment]
Ack’d

**Comment by philiannuzzo** [comment]
Firefox version has been restored with v2.1.5

https://addons.mozilla.org/en-US/firefox/addon/fanlights-io/

Any issues let me know.  Thanks

**Comment by chefBrian** [comment]
Working great! Thanks!
